### ISSUE TITLE
TypeError: __init__() takes at least 3 arguments (1 given)

### ISSUE THREAD

**Issue by Yunxia-li** [uio-bmi/NucMerge#3]
hello:
     I had ran the following command: `python nucmerge.py asb-1 asb-2 pe-1 pe-2 outdir prefix`
But I got these errors:
What does that mean?

```
[bwa_index] Pack FASTA... 0.00 sec
[bwa_index] Construct BWT for the packed sequence...
[bwa_index] 0.19 seconds elapse.
[bwa_index] Update BWT... 0.01 sec
[bwa_index] Pack forward-only FASTA... 0.00 sec
[bwa_index] Construct SA from BWT and Occ... 0.10 sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa index -p /mnt/data/liyunxia/4-project/mito/velvet/Pilon_1/bwa/yyl-nucmer_1 /mnt/data/liyunxia/4-project/mito/velvet/YYL_Mtctgs-zhu2-uniq.fasta
[main] Real time: 0.311 sec; CPU: 0.310 sec
[E::bwa_set_rg] the read group line contained literal <tab> characters -- replace with escaped tabs: \t
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/mnt/data/liyunxia/anaconda3/envs/py2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/mnt/data/liyunxia/anaconda3/envs/py2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/mnt/data/liyunxia/anaconda3/envs/py2/lib/python2.7/multiprocessing/pool.py", line 392, in _handle_results
    task = get()
TypeError: __init__() takes at least 3 arguments (1 given)
```
Hope for your reply
yun

**Comment by kseniakh** [comment]
Hello Yun,

I assume that you've got this error while pilon was executed. Can you tell me whether you have got the results for NucBreak or not?

Ksenia

**Comment by Yunxia-li** [comment]
Hello:
    I didnot get results  for NucBreak.Both the NucBreak1 and NucBreak1 are empty
IN the pilon1 folder, the bwa process results: xxxxx.all.sam was empty. Does that mean bwa process error? But I run BWA, it was successful.
 


At 2019-11-08 00:34:34, "kseniakh" <notifications@github.com> wrote:


Hello Yun,

I assume that you've got this error while pilon was executed. Can you tell me whether you have got the results for NucBreak or not?

Ksenia

**Comment by kseniakh** [comment]
According to this line:
```
[E::bwa_set_rg]` the read group line contained literal <tab> characters -- replace with escaped tabs: \t
Exception in thread Thread-3:
```
the problem occurred during the bwa execution and is related to the read group line problem. 
You can try to run bwa+Pilon yourself to check if this issue is related to NucMerge or not.
